on:
  push:
    branches: [ master ]
  # supports manually triggering the deploy
  workflow_dispatch:
    inputs:
      host:
        required: true
        default: ${{ secrets.HOST }}
    
jobs:
        
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ github.events.input.host }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: .
          target: /var/www/${{ secrets.HOST }}
